2023-03-25 13:48:19,720 - INFO - [MainThread] - Initialized router P4 at port 5004 PID 10220
2023-03-25 13:48:19,722 - INFO - [MainThread] - Adding a connection to LupusreginaBeta
2023-03-25 13:48:19,722 - INFO - [Connect-LupusreginaBeta] - Calling connect_to_rendezvous_point
2023-03-25 13:48:19,722 - INFO - [Connect-LupusreginaBeta] - Connect to rendezvous point LupusreginaBeta
2023-03-25 13:48:19,725 - INFO - [MainThread] - Adding listener for Vulnerar
2023-03-25 13:48:19,725 - INFO - [Establish-Vulnerar] - Establishing RP to Vulnerar
2023-03-25 13:48:19,727 - INFO - [MainThread] - Adding listener for Cornball
2023-03-25 13:48:19,727 - INFO - [Establish-Cornball] - Establishing RP to Cornball
2023-03-25 13:48:19,730 - INFO - [MainThread] - Starting testing thread
2023-03-25 13:48:19,732 - INFO - [Establish-Cornball] - Loading cached NetworkStatusDocument from TorCacheDirStorage: /root/.local/share/torpy/network_status
2023-03-25 13:48:19,747 - INFO - [Establish-Vulnerar] - Loading cached NetworkStatusDocument from TorCacheDirStorage: /root/.local/share/torpy/network_status
2023-03-25 13:48:19,784 - INFO - [TESTER] - Started tester
2023-03-25 13:48:19,792 - INFO - [MainThread] - Starting connection thread
2023-03-25 13:48:19,793 - INFO - [Connect-LupusreginaBeta] - Loading cached NetworkStatusDocument from TorCacheDirStorage: /root/.local/share/torpy/network_status
2023-03-25 13:48:19,819 - INFO - [MainThread] - Starting log thread
2023-03-25 13:48:20,289 - INFO - [Establish-Cornball] - Loading cached DirKeyCertificateList from TorCacheDirStorage: /root/.local/share/torpy/dir_key_certificates
2023-03-25 13:48:20,291 - INFO - [Establish-Cornball] - Connecting to guard node 185.181.61.23:443 (staysafeandgoodluck; Tor 0.4.7.10)... (None)
2023-03-25 13:48:20,357 - INFO - [Establish-Vulnerar] - Loading cached DirKeyCertificateList from TorCacheDirStorage: /root/.local/share/torpy/dir_key_certificates
2023-03-25 13:48:20,359 - INFO - [Establish-Vulnerar] - Connecting to guard node 185.181.61.23:443 (staysafeandgoodluck; Tor 0.4.7.10)... (None)
2023-03-25 13:48:20,393 - INFO - [Connect-LupusreginaBeta] - Loading cached DirKeyCertificateList from TorCacheDirStorage: /root/.local/share/torpy/dir_key_certificates
2023-03-25 13:48:20,396 - INFO - [Establish-Cornball] - Creating new circuit #80000001 with 185.181.61.23:443 (staysafeandgoodluck; Tor 0.4.7.10) router...
2023-03-25 13:48:20,410 - INFO - [Establish-Cornball] - Building -1 hops circuit...
2023-03-25 13:48:20,410 - INFO - [Establish-Cornball] - Extending the circuit #80000001 with 198.244.212.57:443 (Cornball; Tor 0.4.7.10)...
2023-03-25 13:48:20,411 - INFO - [Establish-Cornball] - Getting descriptor for 198.244.212.57:443 (Cornball; Tor 0.4.7.10)...
2023-03-25 13:48:20,415 - INFO - [Establish-Cornball] - Connecting to guard node 185.220.101.80:9000 (CCCStuttgartBer; Tor 0.4.7.13)... (Internal dir client)
2023-03-25 13:48:20,433 - INFO - [Establish-Vulnerar] - Creating new circuit #80000002 with 185.181.61.23:443 (staysafeandgoodluck; Tor 0.4.7.10) router...
2023-03-25 13:48:20,448 - INFO - [Establish-Vulnerar] - Building -1 hops circuit...
2023-03-25 13:48:20,448 - INFO - [Establish-Vulnerar] - Extending the circuit #80000002 with 157.90.179.103:8001 (Vulnerar; Tor 0.4.7.13)...
2023-03-25 13:48:20,511 - INFO - [Connect-LupusreginaBeta] - Connected to rendezvous point LupusreginaBeta
2023-03-25 13:48:20,511 - INFO - [Connect-LupusreginaBeta] - Waiting for peer to open stream
2023-03-25 13:48:20,558 - INFO - [Connect-LupusreginaBeta] - Received cell: <class 'torpy.cells.CellRelay'>
2023-03-25 13:48:20,559 - INFO - [Connect-LupusreginaBeta] - Stream opened successfully
2023-03-25 13:48:20,559 - INFO - [Connect-LupusreginaBeta] - Sending HELLO to peer: b'\x80\x04\x95&\x00\x00\x00\x00\x00\x00\x00]\x94}\x94(\x8c\x07Message\x94\x8c\x05HELLO\x94\x8c\x04Peer\x94\x8c\x02P4\x94ua.'
2023-03-25 13:48:20,647 - INFO - [Establish-Cornball] - Creating new circuit #80000003 with 185.220.101.80:9000 (CCCStuttgartBer; Tor 0.4.7.13) router...
2023-03-25 13:48:20,706 - INFO - [Establish-Cornball] - Building 0 hops circuit...
2023-03-25 13:48:20,706 - INFO - [Establish-Cornball] - Stream #1: creating attached to #80000003 circuit...
2023-03-25 13:48:20,706 - INFO - [Establish-Cornball] - Stream #1: connecting to hsdir
2023-03-25 13:48:20,763 - INFO - [RECEIVER] - Added neighbour P2
2023-03-25 13:48:20,766 - INFO - [RecvLoop_185.220] - Stream #1: connected (remote ip '')
2023-03-25 13:48:21,020 - INFO - [RecvLoop_185.220] - Stream #1: remote disconnected (reason = DONE)
2023-03-25 13:48:21,020 - INFO - [Establish-Cornball] - Stream #1: closing (state = Disconnected)...
2023-03-25 13:48:21,020 - INFO - [Establish-Cornball] - Got descriptor
2023-03-25 13:48:21,021 - INFO - [Establish-Vulnerar] - Getting descriptor for 157.90.179.103:8001 (Vulnerar; Tor 0.4.7.13)...
2023-03-25 13:48:21,024 - INFO - [Establish-Vulnerar] - Connecting to guard node 5.183.170.183:9001 (assassin002; Tor 0.4.7.13)... (Internal dir client)
2023-03-25 13:48:21,063 - INFO - [Establish-Cornball] - <class 'torpy.circuit.TorCircuit'>
2023-03-25 13:48:21,109 - INFO - [Establish-Cornball] - Rendezvous established (CellRelayRendezvousEstablished())
2023-03-25 13:48:21,110 - INFO - [Establish-Cornball] - Waiting for connections at relay Cornball for cookie b'eb688e4f52df90278060' ...
2023-03-25 13:48:21,409 - INFO - [Establish-Vulnerar] - Creating new circuit #80000004 with 5.183.170.183:9001 (assassin002; Tor 0.4.7.13) router...
2023-03-25 13:48:21,511 - INFO - [Establish-Vulnerar] - Building 0 hops circuit...
2023-03-25 13:48:21,511 - INFO - [Establish-Vulnerar] - Stream #2: creating attached to #80000004 circuit...
2023-03-25 13:48:21,511 - INFO - [Establish-Vulnerar] - Stream #2: connecting to hsdir
2023-03-25 13:48:21,606 - INFO - [RecvLoop_5.183.1] - Stream #2: connected (remote ip '')
2023-03-25 13:48:21,813 - INFO - [RecvLoop_5.183.1] - Stream #2: remote disconnected (reason = DONE)
2023-03-25 13:48:21,813 - INFO - [Establish-Vulnerar] - Stream #2: closing (state = Disconnected)...
2023-03-25 13:48:21,813 - INFO - [Establish-Vulnerar] - Got descriptor
2023-03-25 13:48:21,866 - INFO - [Establish-Vulnerar] - <class 'torpy.circuit.TorCircuit'>
2023-03-25 13:48:21,917 - INFO - [Establish-Vulnerar] - Rendezvous established (CellRelayRendezvousEstablished())
2023-03-25 13:48:21,917 - INFO - [Establish-Vulnerar] - Waiting for connections at relay Vulnerar for cookie b'eb688e4f52df90278060' ...
2023-03-25 13:48:27,084 - INFO - [Establish-Vulnerar] - Got REND2 message from Vulnerar
2023-03-25 13:48:27,085 - INFO - [Establish-Vulnerar] - Entered circuit context with id 0x80000002
2023-03-25 13:48:27,085 - INFO - [Establish-Vulnerar] - Stream #3: creating attached to #80000002 circuit...
2023-03-25 13:48:27,085 - INFO - [Establish-Vulnerar] - Stream #3: connecting to ('127.0.0.1', 5000)
2023-03-25 13:48:27,192 - INFO - [RecvLoop_185.181] - Stream #3: connected (remote ip '127.0.0.1')
2023-03-25 13:48:27,287 - INFO - [Establish-Vulnerar] - Sending HELLO to peer
2023-03-25 13:48:27,287 - INFO - [Establish-Vulnerar] - Sending HELLO to peer: b'\x80\x04\x95&\x00\x00\x00\x00\x00\x00\x00]\x94}\x94(\x8c\x07Message\x94\x8c\x05HELLO\x94\x8c\x04Peer\x94\x8c\x02P4\x94ua.'
2023-03-25 13:48:27,289 - INFO - [RECEIVER] - Added neighbour P3
2023-03-25 13:49:09,306 - INFO - [Establish-Cornball] - Got REND2 message from Cornball
2023-03-25 13:49:09,306 - INFO - [Establish-Cornball] - Entered circuit context with id 0x80000001
2023-03-25 13:49:09,307 - INFO - [Establish-Cornball] - Stream #4: creating attached to #80000001 circuit...
2023-03-25 13:49:09,307 - INFO - [Establish-Cornball] - Stream #4: connecting to ('127.0.0.1', 5000)
2023-03-25 13:49:09,414 - INFO - [RecvLoop_185.181] - Stream #4: connected (remote ip '127.0.0.1')
2023-03-25 13:49:09,509 - INFO - [Establish-Cornball] - Sending HELLO to peer
2023-03-25 13:49:09,510 - INFO - [Establish-Cornball] - Sending HELLO to peer: b'\x80\x04\x95&\x00\x00\x00\x00\x00\x00\x00]\x94}\x94(\x8c\x07Message\x94\x8c\x05HELLO\x94\x8c\x04Peer\x94\x8c\x02P4\x94ua.'
2023-03-25 13:49:09,510 - INFO - [RECEIVER] - Added neighbour P5
2023-03-25 13:49:23,140 - INFO - [RecvLoop_185.220] - On destroy: circuit #80000003
2023-03-25 13:49:23,140 - INFO - [RecvLoop_185.220] - Destroy circuit #80000003
2023-03-25 13:49:23,234 - WARNING - [Connect-LupusreginaBeta] - Got SENDME
2023-03-25 13:49:28,368 - INFO - [RecvLoop_5.183.1] - On destroy: circuit #80000004
2023-03-25 13:49:28,368 - INFO - [RecvLoop_5.183.1] - Destroy circuit #80000004
2023-03-25 13:49:59,764 - WARNING - [Connect-LupusreginaBeta] - Got SENDME
2023-03-25 13:49:59,830 - WARNING - [Connect-LupusreginaBeta] - Got SENDME
2023-03-25 13:50:33,796 - WARNING - [Connect-LupusreginaBeta] - Got SENDME
2023-03-25 13:51:10,647 - WARNING - [Connect-LupusreginaBeta] - Got SENDME
2023-03-25 13:51:10,669 - WARNING - [Connect-LupusreginaBeta] - Got SENDME
2023-03-25 13:51:49,678 - WARNING - [Connect-LupusreginaBeta] - Got SENDME
2023-03-25 13:52:24,954 - WARNING - [Connect-LupusreginaBeta] - Got SENDME
2023-03-25 13:52:24,963 - WARNING - [Connect-LupusreginaBeta] - Got SENDME
2023-03-25 13:53:05,062 - WARNING - [Connect-LupusreginaBeta] - Got SENDME
2023-03-25 13:53:40,027 - INFO - [Thread-4] - Adding P2 to list of inactive
2023-03-25 13:53:40,027 - INFO - [Thread-4] - Removing P2 from neighbours
2023-03-25 13:54:15,056 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:54:15,057 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:54:15,219 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:54:15,537 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:54:15,547 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:54:15,753 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:54:19,995 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:54:20,029 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:54:20,032 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:54:20,060 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:54:20,098 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:54:20,099 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:54:20,123 - INFO - [CONNECTION] - Loading cached NetworkStatusDocument from TorCacheDirStorage: /root/.local/share/torpy/network_status
2023-03-25 13:54:20,159 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:54:20,359 - INFO - [CONNECTION] - Loading cached DirKeyCertificateList from TorCacheDirStorage: /root/.local/share/torpy/dir_key_certificates
2023-03-25 13:54:20,365 - INFO - [MainThread] - ['ESTABLISH', 'Chimera2', b'efd6a88be487391d1a34']
2023-03-25 13:54:20,365 - INFO - [MainThread] - Got ESTABLISH to relay Chimera2:b'efd6a88be487391d1a34' via staysafeandgoodluck
2023-03-25 13:54:20,366 - INFO - [Establish-Chimera2] - Establishing RP to Chimera2
2023-03-25 13:54:20,379 - INFO - [Establish-Chimera2] - Loading cached NetworkStatusDocument from TorCacheDirStorage: /root/.local/share/torpy/network_status
2023-03-25 13:54:20,692 - INFO - [Establish-Chimera2] - Loading cached DirKeyCertificateList from TorCacheDirStorage: /root/.local/share/torpy/dir_key_certificates
2023-03-25 13:54:20,695 - INFO - [Establish-Chimera2] - Connecting to guard node 185.181.61.23:443 (staysafeandgoodluck; Tor 0.4.7.10)... (None)
2023-03-25 13:54:20,753 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:54:20,768 - INFO - [Establish-Chimera2] - Creating new circuit #80000005 with 185.181.61.23:443 (staysafeandgoodluck; Tor 0.4.7.10) router...
2023-03-25 13:54:20,789 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:54:20,794 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:54:20,795 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:54:20,797 - INFO - [Establish-Chimera2] - Building -1 hops circuit...
2023-03-25 13:54:20,797 - INFO - [Establish-Chimera2] - Extending the circuit #80000005 with 149.56.22.133:80 (Chimera2; Tor 0.4.7.13)...
2023-03-25 13:54:20,801 - INFO - [Establish-Chimera2] - Getting descriptor for 149.56.22.133:80 (Chimera2; Tor 0.4.7.13)...
2023-03-25 13:54:20,806 - INFO - [Establish-Chimera2] - Connecting to guard node 198.98.59.102:443 (r4v3nrelay; Tor 0.4.7.12)... (Internal dir client)
2023-03-25 13:54:20,855 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:54:20,968 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:54:21,284 - INFO - [Establish-Chimera2] - Creating new circuit #80000006 with 198.98.59.102:443 (r4v3nrelay; Tor 0.4.7.12) router...
2023-03-25 13:54:21,403 - INFO - [Establish-Chimera2] - Building 0 hops circuit...
2023-03-25 13:54:21,404 - INFO - [Establish-Chimera2] - Stream #5: creating attached to #80000006 circuit...
2023-03-25 13:54:21,404 - INFO - [Establish-Chimera2] - Stream #5: connecting to hsdir
2023-03-25 13:54:21,513 - INFO - [RecvLoop_198.98.] - Stream #5: connected (remote ip '')
2023-03-25 13:54:21,825 - INFO - [RecvLoop_198.98.] - Stream #5: remote disconnected (reason = DONE)
2023-03-25 13:54:21,826 - INFO - [Establish-Chimera2] - Stream #5: closing (state = Disconnected)...
2023-03-25 13:54:21,826 - INFO - [Establish-Chimera2] - Got descriptor
2023-03-25 13:54:22,513 - INFO - [Establish-Chimera2] - <class 'torpy.circuit.TorCircuit'>
2023-03-25 13:54:22,634 - INFO - [Establish-Chimera2] - Rendezvous established (CellRelayRendezvousEstablished())
2023-03-25 13:54:22,634 - INFO - [Establish-Chimera2] - Waiting for connections at relay Chimera2 for cookie b'efd6a88be487391d1a34' ...
2023-03-25 13:54:23,739 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:54:24,660 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:54:24,701 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:54:25,120 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:54:25,809 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:54:27,309 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:54:29,785 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:54:29,812 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:54:29,822 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:54:29,823 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:54:30,159 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:54:30,374 - INFO - [CONNECTION] - Sending JOIN to P5 for relay Chimera2 with cookie b'efd6a88be487391d1a34'
2023-03-25 13:54:30,756 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:54:31,083 - INFO - [Thread-4] - Adding P5 to list of inactive
2023-03-25 13:54:31,083 - INFO - [Thread-4] - Removing P5 from neighbours
2023-03-25 13:54:32,875 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:54:32,920 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:54:32,922 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:54:32,923 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:54:32,926 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:54:32,928 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:54:32,929 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:54:32,979 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:54:34,085 - INFO - [Establish-Chimera2] - Got REND2 message from Chimera2
2023-03-25 13:54:34,087 - INFO - [Establish-Chimera2] - Entered circuit context with id 0x80000005
2023-03-25 13:54:34,087 - INFO - [Establish-Chimera2] - Stream #6: creating attached to #80000005 circuit...
2023-03-25 13:54:34,087 - INFO - [Establish-Chimera2] - Stream #6: connecting to ('127.0.0.1', 5000)
2023-03-25 13:54:34,340 - INFO - [RecvLoop_185.181] - Stream #6: connected (remote ip '127.0.0.1')
2023-03-25 13:54:34,491 - INFO - [Establish-Chimera2] - Sending HELLO to peer
2023-03-25 13:54:34,491 - INFO - [Establish-Chimera2] - Sending HELLO to peer: b'\x80\x04\x95&\x00\x00\x00\x00\x00\x00\x00]\x94}\x94(\x8c\x07Message\x94\x8c\x05HELLO\x94\x8c\x04Peer\x94\x8c\x02P4\x94ua.'
2023-03-25 13:54:34,493 - INFO - [RECEIVER] - Added neighbour P5
2023-03-25 13:54:35,171 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:54:36,246 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:54:36,279 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:54:36,280 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:54:36,282 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:55:14,989 - ERROR - [Establish-Cornball] - recv timeout
2023-03-25 13:55:14,989 - INFO - [Establish-Cornball] - Closing connection Establish-Cornball
2023-03-25 13:55:14,989 - INFO - [Establish-Cornball] - Stream #4: closing (state = Connected)...
2023-03-25 13:55:14,990 - INFO - [Establish-Cornball] - Destroy circuit #80000001
2023-03-25 13:55:14,990 - INFO - [Establish-Cornball] - Closing guard connections (None)...
2023-03-25 13:55:31,427 - INFO - [RecvLoop_198.98.] - On destroy: circuit #80000006
2023-03-25 13:55:31,427 - INFO - [RecvLoop_198.98.] - Destroy circuit #80000006
2023-03-25 13:56:57,914 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:56:57,978 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:56:57,979 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:56:58,061 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:56:58,063 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:56:58,065 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:57:01,147 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:57:03,004 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:57:05,002 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:57:05,011 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:57:05,011 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:57:05,120 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:57:06,553 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:57:06,700 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:57:08,024 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:57:09,972 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:57:11,217 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:57:12,228 - INFO - [Thread-4] - Adding P5 to list of inactive
2023-03-25 13:57:12,228 - INFO - [Thread-4] - Removing P5 from neighbours
2023-03-25 13:57:12,455 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:57:12,967 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:57:13,041 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:57:13,042 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:57:13,115 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:57:13,116 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:57:15,153 - ERROR - [RECEIVER] - 'P5'
2023-03-25 13:57:15,197 - ERROR - [RECEIVER] - 'P5'
2023-03-25 13:57:18,070 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:57:20,074 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:57:20,165 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:57:20,167 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:57:20,219 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:57:23,091 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:57:24,996 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:57:28,114 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:57:28,276 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:57:28,279 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:57:28,420 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:57:28,422 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:57:30,176 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:57:30,557 - INFO - [CONNECTION] - Neighbour connections (1) less than MIN_NEIGHBOUR_CONNECTIONS (2)
2023-03-25 13:57:30,558 - INFO - [CONNECTION] - Candidate peers: ['P6', 'P8', 'P1']
2023-03-25 13:57:30,558 - INFO - [CONNECTION] - Highest cost peers: [('P2', 4685), ('P8', 4676), ('P7', 3555), ('P6', 3370), ('P1', 2472), ('P5', 1638), ('P3', 1143), ('P4', 0)]
2023-03-25 13:57:30,568 - INFO - [CONNECTION] - Loading cached NetworkStatusDocument from TorCacheDirStorage: /root/.local/share/torpy/network_status
2023-03-25 13:57:30,776 - INFO - [CONNECTION] - Loading cached DirKeyCertificateList from TorCacheDirStorage: /root/.local/share/torpy/dir_key_certificates
2023-03-25 13:57:30,783 - INFO - [MainThread] - ['ESTABLISH', 'TORKeFFORG12', b'38f2e45ed1e749a83cec']
2023-03-25 13:57:30,783 - INFO - [MainThread] - Got ESTABLISH to relay TORKeFFORG12:b'38f2e45ed1e749a83cec' via staysafeandgoodluck
2023-03-25 13:57:30,784 - INFO - [Establish-TORKeFFORG12] - Establishing RP to TORKeFFORG12
2023-03-25 13:57:30,800 - INFO - [Establish-TORKeFFORG12] - Loading cached NetworkStatusDocument from TorCacheDirStorage: /root/.local/share/torpy/network_status
2023-03-25 13:57:30,997 - INFO - [Establish-TORKeFFORG12] - Loading cached DirKeyCertificateList from TorCacheDirStorage: /root/.local/share/torpy/dir_key_certificates
2023-03-25 13:57:30,999 - INFO - [Establish-TORKeFFORG12] - Connecting to guard node 185.181.61.23:443 (staysafeandgoodluck; Tor 0.4.7.10)... (None)
2023-03-25 13:57:31,064 - INFO - [Establish-TORKeFFORG12] - Creating new circuit #80000007 with 185.181.61.23:443 (staysafeandgoodluck; Tor 0.4.7.10) router...
2023-03-25 13:57:31,079 - INFO - [Establish-TORKeFFORG12] - Building -1 hops circuit...
2023-03-25 13:57:31,079 - INFO - [Establish-TORKeFFORG12] - Extending the circuit #80000007 with 193.189.100.205:443 (TORKeFFORG12; Tor 0.4.7.13)...
2023-03-25 13:57:31,080 - INFO - [Establish-TORKeFFORG12] - Getting descriptor for 193.189.100.205:443 (TORKeFFORG12; Tor 0.4.7.13)...
2023-03-25 13:57:31,084 - INFO - [Establish-TORKeFFORG12] - Connecting to guard node 213.164.206.145:9001 (vpskilobug; Tor 0.4.7.13)... (Internal dir client)
2023-03-25 13:57:31,160 - INFO - [Establish-TORKeFFORG12] - Creating new circuit #80000008 with 213.164.206.145:9001 (vpskilobug; Tor 0.4.7.13) router...
2023-03-25 13:57:31,181 - INFO - [Establish-TORKeFFORG12] - Building 0 hops circuit...
2023-03-25 13:57:31,181 - INFO - [Establish-TORKeFFORG12] - Stream #7: creating attached to #80000008 circuit...
2023-03-25 13:57:31,181 - INFO - [Establish-TORKeFFORG12] - Stream #7: connecting to hsdir
2023-03-25 13:57:31,199 - INFO - [RecvLoop_213.164] - Stream #7: connected (remote ip '')
2023-03-25 13:57:31,419 - INFO - [RecvLoop_213.164] - Stream #7: remote disconnected (reason = DONE)
2023-03-25 13:57:31,420 - INFO - [Establish-TORKeFFORG12] - Stream #7: closing (state = Disconnected)...
2023-03-25 13:57:31,420 - INFO - [Establish-TORKeFFORG12] - Got descriptor
2023-03-25 13:57:31,488 - INFO - [Establish-TORKeFFORG12] - <class 'torpy.circuit.TorCircuit'>
2023-03-25 13:57:31,512 - INFO - [Establish-TORKeFFORG12] - Rendezvous established (CellRelayRendezvousEstablished())
2023-03-25 13:57:31,512 - INFO - [Establish-TORKeFFORG12] - Waiting for connections at relay TORKeFFORG12 for cookie b'38f2e45ed1e749a83cec' ...
2023-03-25 13:57:33,135 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:57:33,377 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:57:33,388 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:57:33,390 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:57:33,495 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:57:38,155 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:57:40,104 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:57:40,792 - INFO - [CONNECTION] - Sending JOIN to P8 at relay TORKeFFORG12
2023-03-25 13:57:41,398 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:57:41,401 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:57:41,405 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:57:41,504 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:57:43,059 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:57:47,896 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:57:47,918 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:57:47,919 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:57:48,025 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:57:48,172 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:57:53,120 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:57:55,065 - ERROR - [RecvLoop_185.181] - Some handle errors
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 224, in _do_recv
    self._handler_mgr.handle(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 280, in handle
    handler(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 43, in wrapped
    return func(*args_new, **kwargs)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/guard.py", line 127, in _on_relay
    circuit.handle_relay(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 456, in handle_relay
    circuit_node, inner_cell = self._decrypt(cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 522, in _decrypt
    return from_node, relay_cell.get_decrypted()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 234, in get_decrypted
    assert self._checked
AssertionError
2023-03-25 13:57:56,161 - ERROR - [Establish-Chimera2] - recv timeout
2023-03-25 13:57:56,161 - INFO - [Establish-Chimera2] - Closing connection Establish-Chimera2
2023-03-25 13:57:56,161 - INFO - [Establish-Chimera2] - Stream #6: closing (state = Connected)...
2023-03-25 13:57:56,162 - INFO - [Establish-Chimera2] - Destroy circuit #80000005
2023-03-25 13:57:56,163 - INFO - [Establish-Chimera2] - Closing guard connections (None)...
2023-03-25 14:21:31,810 - ERROR - [Establish-Vulnerar] - recv timeout
2023-03-25 14:21:31,838 - INFO - [Establish-Vulnerar] - Closing connection Establish-Vulnerar
2023-03-25 14:21:31,871 - INFO - [Establish-Vulnerar] - Stream #3: closing (state = Connected)...
2023-03-25 14:21:32,078 - INFO - [Establish-Vulnerar] - Destroy circuit #80000002
2023-03-25 14:21:32,086 - INFO - [Establish-Vulnerar] - Closing guard connections (None)...
2023-03-25 14:21:33,402 - INFO - [RecvLoop_213.164] - On destroy: circuit #80000008
2023-03-25 14:21:33,402 - INFO - [RecvLoop_213.164] - Destroy circuit #80000008
2023-03-25 14:21:33,418 - WARNING - [RecvLoop_185.181] - CellPadding has some unnecessary data: b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
2023-03-25 14:21:33,425 - ERROR - [RecvLoop_185.181] - CellPadding() was received but no handlers for it
2023-03-25 14:21:33,446 - WARNING - [RecvLoop_185.181] - CellPadding has some unnecessary data: b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
2023-03-25 14:21:33,447 - ERROR - [RecvLoop_185.181] - CellPadding() was received but no handlers for it
2023-03-25 14:21:33,785 - WARNING - [RecvLoop_185.181] - CellPadding has some unnecessary data: b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
2023-03-25 14:21:33,790 - ERROR - [RecvLoop_185.181] - CellPadding() was received but no handlers for it
2023-03-25 14:21:33,838 - WARNING - [RecvLoop_185.181] - CellPadding has some unnecessary data: b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
2023-03-25 14:21:33,839 - ERROR - [RecvLoop_185.181] - CellPadding() was received but no handlers for it
2023-03-25 14:21:36,214 - INFO - [CONNECTION] - Neighbour connections (1) less than MIN_NEIGHBOUR_CONNECTIONS (2)
2023-03-25 14:21:36,215 - INFO - [CONNECTION] - Candidate peers: ['P6', 'P8', 'P1']
2023-03-25 14:21:36,215 - INFO - [CONNECTION] - Highest cost peers: [('P2', 4685), ('P8', 4676), ('P7', 3555), ('P6', 3370), ('P1', 1884), ('P5', 1638), ('P3', 470), ('P4', 0)]
2023-03-25 14:21:36,234 - INFO - [CONNECTION] - Loading cached NetworkStatusDocument from TorCacheDirStorage: /root/.local/share/torpy/network_status
2023-03-25 14:21:36,446 - WARNING - [HEART BEAT] - socket already closed
2023-03-25 14:21:37,712 - INFO - [CONNECTION] - Loading cached DirKeyCertificateList from TorCacheDirStorage: /root/.local/share/torpy/dir_key_certificates
2023-03-25 14:21:37,734 - INFO - [MainThread] - ['ESTABLISH', 'Digitalcourage4ip3a', b'c7a16a547b10d53dcf73']
2023-03-25 14:21:37,734 - INFO - [MainThread] - Got ESTABLISH to relay Digitalcourage4ip3a:b'c7a16a547b10d53dcf73' via staysafeandgoodluck
2023-03-25 14:21:37,735 - INFO - [Establish-Digitalcourage4ip3a] - Establishing RP to Digitalcourage4ip3a
2023-03-25 14:21:37,791 - INFO - [Establish-Digitalcourage4ip3a] - Loading cached NetworkStatusDocument from TorCacheDirStorage: /root/.local/share/torpy/network_status
2023-03-25 14:21:38,774 - INFO - [Thread-4] - Adding P3 to list of inactive
2023-03-25 14:21:38,775 - INFO - [Thread-4] - Removing P3 from neighbours
2023-03-25 14:21:39,998 - INFO - [Establish-Digitalcourage4ip3a] - Loading cached DirKeyCertificateList from TorCacheDirStorage: /root/.local/share/torpy/dir_key_certificates
2023-03-25 14:21:40,003 - INFO - [Establish-Digitalcourage4ip3a] - Connecting to guard node 185.181.61.23:443 (staysafeandgoodluck; Tor 0.4.7.10)... (None)
2023-03-25 14:21:40,104 - INFO - [Establish-Digitalcourage4ip3a] - Creating new circuit #80000009 with 185.181.61.23:443 (staysafeandgoodluck; Tor 0.4.7.10) router...
2023-03-25 14:21:40,152 - INFO - [Establish-Digitalcourage4ip3a] - Building -1 hops circuit...
2023-03-25 14:21:40,152 - INFO - [Establish-Digitalcourage4ip3a] - Extending the circuit #80000009 with 185.220.102.250:443 (Digitalcourage4ip3a; Tor 0.4.7.13)...
2023-03-25 14:21:40,170 - INFO - [Establish-Digitalcourage4ip3a] - Getting descriptor for 185.220.102.250:443 (Digitalcourage4ip3a; Tor 0.4.7.13)...
2023-03-25 14:21:40,191 - INFO - [Establish-Digitalcourage4ip3a] - Connecting to guard node 185.177.126.118:443 (blix; Tor 0.4.7.10)... (Internal dir client)
2023-03-25 14:21:40,390 - INFO - [Establish-Digitalcourage4ip3a] - Creating new circuit #8000000a with 185.177.126.118:443 (blix; Tor 0.4.7.10) router...
2023-03-25 14:21:40,440 - INFO - [Establish-Digitalcourage4ip3a] - Building 0 hops circuit...
2023-03-25 14:21:40,441 - INFO - [Establish-Digitalcourage4ip3a] - Stream #8: creating attached to #8000000a circuit...
2023-03-25 14:21:40,441 - INFO - [Establish-Digitalcourage4ip3a] - Stream #8: connecting to hsdir
2023-03-25 14:21:40,534 - INFO - [RecvLoop_185.177] - Stream #8: connected (remote ip '')
2023-03-25 14:21:40,797 - INFO - [RecvLoop_185.177] - Stream #8: remote disconnected (reason = DONE)
2023-03-25 14:21:40,802 - INFO - [Establish-Digitalcourage4ip3a] - Stream #8: closing (state = Disconnected)...
2023-03-25 14:21:40,802 - INFO - [Establish-Digitalcourage4ip3a] - Got descriptor
2023-03-25 14:21:41,017 - INFO - [Establish-Digitalcourage4ip3a] - <class 'torpy.circuit.TorCircuit'>
2023-03-25 14:21:41,072 - INFO - [Establish-Digitalcourage4ip3a] - Rendezvous established (CellRelayRendezvousEstablished())
2023-03-25 14:21:41,073 - INFO - [Establish-Digitalcourage4ip3a] - Waiting for connections at relay Digitalcourage4ip3a for cookie b'c7a16a547b10d53dcf73' ...
